Traceback (most recent call last):
  File "/home/ryan/.local/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 1107, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/miniconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/miniconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/opt/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 852, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
## # enter your work here - Uncomment the following lines of code and make necessary changes

# def power_func(x,a,b):
#     '''fits the linear equation y = kx
#     This equation can be replaced by polynomial or exponential 
#     as per the fitting goals of the problem'''
#     return ??

# Q = np.array([11.37,9.84,9.00,8.10,7.00,6.00,4.34])   # LPM
# dp = np.array([55,44,34,28,22,18,8])                  # mm of water

# k,pcov=??
# a = k[0]
# b = k[1]

# print("Caliberation equation for venturi meter is Q = %1.3f \u0394p^%1.3f "%(a,b))

# plt.plot(dp,Q,'o',label='experiment')
# plt.plot(dp,power_func(dp,a,b),label='model')
# plt.legend()
# plt.xlabel(r'$\sqrt{\Delta p}$, (mm of water)')
# plt.ylabel('Q (LPM)')


import check_lab03 as p
p.check_p01(a,b)

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-4-4db0d5ae2610>[0m in [0;36m<module>[0;34m[0m
[1;32m     24[0m [0;34m[0m[0m
[1;32m     25[0m [0;32mimport[0m [0mcheck_lab03[0m [0;32mas[0m [0mp[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 26[0;31m [0mp[0m[0;34m.[0m[0mcheck_p01[0m[0;34m([0m[0ma[0m[0;34m,[0m[0mb[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'a' is not defined
NameError: name 'a' is not defined

